version: '3'

services:
  db:
    image: mdillon/postgis
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cykel
      - POSTGRES_PASSWORD=password

  redis:
    image: redis

  cykel-worker: &default
    build: .
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=fooooo
      - ALLOWED_HOSTS=0.0.0.0,localhost
      - DEBUG=1
      - DATABASE_URL=postgis://postgres:password@db:5432/cykel
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: celery -A cykel worker -l INFO -B

  cykel:
    <<: *default
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  voorwiel:
    image: stadtulm/voorwiel
    ports:
      - "8080:80"

volumes:
  data:
